### ISSUE TITLE
GUI for exploring/debugging renderers of a canvas

### ISSUE THREAD

**Issue by hageldave** [hageldave/JPlotter#35]
This feature contains the development of a little gui tool that can show all the `Renderer`s that are on a `JPlotterCanvas`.
The canvas renders its contents through the set renderer (see `JPlotterCanvas.getRenderer()`). Such a renderer can consist of several other renderers e.g. `ChainedRenderer`, `CompleteRenderer`, `CoordsSysRenderer`, ... which ultimately use some of the 'core'-renderers that actually take care of drawing onto the canvas (such as `Points-`, `Lines-`, or `TextRenderer`).

**The gui tool should be able to show this structure of nested renderers, preferably in a tree like structure such as `javax.swing.JTree`.** ([resource for how to JTree](https://docs.oracle.com/javase/tutorial/uiswing/components/tree.html))

Since we can never be sure what kind of renderer is set on the canvas (could be a coordsys, but could also be a third party renderer implementation, or a renderer that we will add to JPlotter somewhen in the future), the implementation should use the java reflection API to search the renderer object for nested instances of the `Renderer` interface. Here is a quick [overview of the reflection API](https://www.baeldung.com/java-reflection).

As this is a larger system to complement JPlotter, we should discuss if it makes sense to make it a standalone project that is available in a different maven artifact (which helps in separating core functionality from special features but has other downsides)

---

Follow up tasks to the display of nested renderers are
- display of render items (such as `Lines`, `Points`, `Triangles` objects)
- editable renderer properties (e.g. `PointsRenderer.glyphScaling` or `Renderer.setEnabled(boolean)`) 

These will be further concretized once we are done with the display

**Comment by lvcarx** [comment]
### What it should do 

As described above we wanted to develop a small GUI tool, that shows the active canvas and all the underlying renderers & renderables.
They are displayed in a tree structure in the gui tool, where all of the tree items are selectable (as shown in the screenshot).

![Pasted Graphic](https://user-images.githubusercontent.com/52721603/173192518-2ff55d54-2bbe-41bb-bb22-ea0089301267.png)


Many of the renderer & renderable properties are also editable, which updates the corresponding canvas and therefore is directly represented/visible in it.
If necessary more even more object properties can be edited, but this will be explained in detail in the next sections.

There are also other bonus features like export svg/pdf functionality, but the core functionality of the tool is what’s described above.

### Extendability

After describing what the tool should be able to do, there are some other goals to achieve:

- Easy extendability of the functionality of the gui tool (e.g. making more or newly introduced object properties editable)
- This should be a very easy thing to do with little amount of code to write

### How we achieve it

_How to retrieve the information_

As @hageldave described in the introduction post, we use reflections to get the canvas and all of its renderers (and their renderers and so on) at runtime.
With that information a tree is constructed as seen in the screenshot on the left above.

As we save all the traversed renderers & renderables in the tree, we can also retrieve all their object properties later by reflections, when an entry is selected.

_How to display and edit the information_

So now we have an idea on how to get all the information needed to display and manipulate the object properties as seen in the screenshot.
But how are these swing components (in the red boxes) created?
To illustrate this we think of each of these red boxes as so called „Panels“, which basically are just swing container panels that contain the shown components.

![Manipulate object properties](https://user-images.githubusercontent.com/52721603/173192538-dac3b21a-52ef-497e-927b-fffc120ad8a1.png)


_How to create and register a Panel_

But how are these panels created and then registered? First we will answer how a panel is created.
To create a panel the „ControlPanelCreator“ interface (and its „create“ method) has to be implemented. This interface’s „create“ method is provided with all the necessary parameters to manipulate the object properties (such as the object, setter & getter methods -> use reflections again to call those).
In the „create“ method there is also a „panelContainer“ JPanel passed as an argument. This JPanel acts as a wrapper for all the components that should be displayed in the panel. Therefore they should be added to this panelContainer.
Here is an example:

**ButtonCreator.class**

```
public class ButtonCreator implements ControlPanelCreator {
    @Override
    public JPanel create(JPlotterCanvas canvas, Object obj, JPanel panelContainer, Method setter, Method getter) throws Exception {
        boolean currentValue = (boolean) getter.invoke(obj);
        JButton button = new JButton(String.valueOf(currentValue));
        button.addActionListener(e -> {
            try {
                setter.invoke(obj, !(boolean) getter.invoke(obj));
                button.setText(String.valueOf((boolean) getter.invoke(obj)));
            } catch (IllegalAccessException | InvocationTargetException ex) {
                throw new RuntimeException(ex);
            }
            canvas.scheduleRepaint();
        });
        panelContainer.add(button);
        return panelContainer;
    }
}
```

The next question is how these panels now will be registered so that the debugging tool knows 1) that they exist and 2) where to insert them.
For that we introduced two new annotation types: „@DebugGetter“ and „@DebugSetter“. As the name implies, the getters and setters of the properties that you want to control have to be annotated with these annotations.
To connect the getter and the setter a key has to be provided to both annotations. The DebugSetter also expects a ControlPanelCreator -> e.g. the one that you created.

See an example here:

**(Methods from Lines.class)**

```
@Override
@DebugGetter(key = "hidden")
public boolean isHidden() {
	return hidden;
}

/**
 * Hides or unhides this Lines object, i.e. sets the {@link #isHidden()} field
 * value. When hidden, renderers will not draw it.
 * @param hide true when hiding
 * @return this for chaining
 */
@DebugSetter(key = "hidden", creator = ButtonCreator.class)
public Lines hide(boolean hide) {
	this.hidden = hide;
	return this;
}
```

### The special case: Only display the properties without making them editable 

If you only want to display the properties, without possibly manipulating them, there is a separate area for that, called „Additional information“.


![Pasted Graphic 1](https://user-images.githubusercontent.com/52721603/173192551-a0d6531b-d0e0-4c72-a0f3-4256f2afb114.png)

As a setter isn’t needed here, you only need to annotate the getter with the DebugGetter annotation, as seen below:

```
/**
 * @return the line segments list.
 * Make sure to call {@link #setDirty()} when manipulating.
 */
@DebugGetter(key = "segments")
public ArrayList<SegmentDetails> getSegments() {
	return segments;
}

```
