### ISSUE TITLE
Isolines not rendering the entire view

### ISSUE THREAD

**Issue by crowlogic** [hageldave/JPlotter#42]
See 

https://github.com/crowlogic/arb4j/blob/master/src/arb/viz/gl/IsolinesViz.java

![Screenshot from 2022-06-19 02-08-30](https://user-images.githubusercontent.com/41244135/174469917-13b80ec8-be0a-4ae6-89c1-930835769e64.png)

**Comment by hageldave** [comment]
Hey, thanks for the issue. I didn't have time yet to look into this in detail, but I think the problem is that the scalar field samples X,Y,Z are only computed once for a predefined (or initial) view. The isolines and isobands are then computed on these samples. When changing the view, more (or new) samples and resulting isolines and bands need to be computed so that they can be shown.

I'll have to verify my guess though. Probably tonight.

**Comment by hageldave** [comment]
okay yes, that is in fact the problem here. First I'd suggest changing the code to not use hard coded ranges from -4 to 4 as the example does, but instead have a variable for the sampling area. Like so (introducing `samplingArea`)
```java
double[][] X = new double[resolution][resolution];
double[][] Y = new double[resolution][resolution];
double[][] Z = new double[resolution][resolution];
Rectangle2D samplingArea = new Rectangle2D.Double(-4, -4, 8, 8);
for(int j=0; j<X.length;j++) {
	for(int i=0; i<X[0].length; i++) {
		double x = i*samplingArea.getWidth()/(resolution-1) +samplingArea.getX();
		double y = j*samplingArea.getHeight()/(resolution-1) +samplingArea.getY();
		double z = f.applyAsDouble(x, y);
		X[j][i] = x;
		Y[j][i] = y;
		Z[j][i] = z;
	}
}
```

If you want to be able to "explore" the scalar field, i.e. change the view by panning or zooming in and out and always have the full view covered with scalar field visualization, then you'll need to come up with a more sophisticated mechanism for creating the samples, isolines, and isobands. These would need to be created or updated dynamically based on the coordinate system's view. You can listen on view change events of the coordinate system like so
```java
coordsys.addCoordinateViewListener(new CoordinateViewListener() {
	@Override
	public void coordinateViewChanged(CoordSysRenderer src, Rectangle2D view) {
		// do something when the view changes
	}
});
```
The most naive approach would be to throw away all samples, isolines, and isoband triangles when the view changes (`contourlines.removeAllSegments()`) and then compute new samples and so on for the current view. This will most likely be very computationally intense since the view listener can be called several times per second when panning.

A better but more complex solution would be to divide 2D space into rectangular chunks, e.g. each chunk is 8x8 in size. Each chunk has its own samples and iso elements for the area that it covers. When the view changes, you'll need to fetch these elements from the chunks that intersect with the view,  and create these elements for such chunks which are intersecting the view for the first time. This is similar to how world data is loaded in video games (such as Minecraft, hence the 'chunk' terminology).

Is that what you wanted to achieve?

**Comment by crowlogic** [comment]
Hey Dave ! Thank you so much for responding so quickly.
That is precisely what I want to do, I was inspired by the LWJGL demo that
looked like minecraft,
I want to make a 3d complex surface flyover/walkthru.. I've created a
branch of the jplotter fork called arb4j where
I want to see about making versions of the algos using the Real and Complex
types directly
I just finished the piece of code that uses memory mapped DirectByteBuffers
to allocate storage for the matrix of pairs of Complex numbers (for the
function and its derivatives evaluated on a grid to be made into a domain
color plot) .
I want to port this code to use jplotter, and I wonder if you have
considered opengl scaling rather than scaling the coordinate system, then
the anti-aliasing would look really nice when zoomed out.
I would like to gain the translation and zooming features of jplotter
there, so perhaps I should change it so that a pair of  50x50  Complex
matrices are computed as chunks and cached and wouldn't need to be
recomputed.. you could vary the colormap features dynamically without
having to recalculate the rather intensive calculations required for each
pixel. These chunks could be rendered as they came into view like you
suggest, and I was also noticing it would be rather easy to implement  a
render-service over RMI so that a machine could request another computer to
blocks for it.. a 50x50 Complex matrix would require 50x50x96=~235Kbytes

**Comment by hageldave** [comment]
Sorry for the late reply, was very busy.
>  I wonder if you have
considered opengl scaling rather than scaling the coordinate system, then
the anti-aliasing would look really nice when zoomed out.

I'm not sure if I understand correctly. The primitive renderers (lines,points,triangles and so on) use a view transfrom similar to a camera in 3D for determining which elements are rendered. Scaling and translation is expressed in the view transform, just the regular stuff I'd say. But I think that is not the scaling you are talking about (?), because you are referring to anti-aliasing. So with the opengl rendererers, anti-aliasing is realized through multisampling (MSAA). Maybe you are suggesting supersampling anti-aliasing (SSAA), where everything is scaled up during rendering and then rescaled afterwards? I think I decided for MSAA because it has a better perfromance.

**Comment by crowlogic** [comment]
Yes i was thinking of drawing things at a higher resolution and then
downsampling. This would get rid of the pixelation effect when drawing
stuff with lots of gradients . I'm semi retired I swore I would never get
busy again. Jplotter is awesome thanks for making it !
