### ISSUE TITLE
BarycentricGradientPaint triangle does not overlap with a triangle painted using drawPolygon

### ISSUE THREAD

**Issue by hrkalona** [hageldave/JPlotter#54]
Using this, you can see that a white line appears, even if the fill takes place after the polygonFill
public class TriangleExample {

    public static void main(String[] args) throws Exception {
        // Create a new BufferedImage object
        int width = 400;
        int height = 400;
        BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);

        // Get the Graphics2D object
        Graphics2D g2d = image.createGraphics();

        // Define three vertices of the triangle
        int[] xPoints = {50, 350, 200};
        int[] yPoints = {50, 50, 350};

        // Define three colors for the gradient
        Color color1 = Color.RED;
        Color color2 = Color.GREEN;
        Color color3 = Color.BLUE;

        // Draw the triangle with a linear gradient
        Polygon triangle = new Polygon(xPoints, yPoints, 3);
        Point2D p1 = new Point2D.Float(xPoints[0], yPoints[0]);
        Point2D p2 = new Point2D.Float(xPoints[1], yPoints[1]);
        Point2D p3 = new Point2D.Float(xPoints[2], yPoints[2]);

        g2d.setColor(Color.WHITE);
        g2d.drawPolygon(triangle);
        BarycentricGradientPaint gradient = new BarycentricGradientPaint(p1, p2, p3, color1, color2, color3);
        g2d.setPaint(gradient);
        g2d.fill(triangle);

        // Save the image to a file
        File output = new File("triangle.png");
        ImageIO.write(image, "png", output);
    }

**Comment by hageldave** [comment]
oh I'm sorry, I've just seen this now. Let me look into this.

**Comment by hageldave** [comment]
Okay, so I see what you mean. I made another test against a regular color fill and it seems like it is expected that you see the outline.
```java
g2d.setColor(Color.WHITE);
g2d.drawPolygon(triangle);

g2d.setColor(Color.BLUE);
g2d.fillPolygon(triangle);
```
![solid_fill](https://user-images.githubusercontent.com/2974361/231879613-7b9b274b-f19b-45b4-8447-6d2f49b4ca19.png)

whereas the barycentric gradient fill produces the following:
```java
g2d.setColor(Color.WHITE);
g2d.drawPolygon(triangle);

g2d.setPaint(new BarycentricGradientPaint(p1, p2, p3, color1, color2, color3));
g2d.fillPolygon(triangle);
```
![gradient_fill](https://user-images.githubusercontent.com/2974361/231880047-672fb9d9-c210-4c41-bf32-fa269d7be677.png)

However, it appears that the right edge is thicker, meaning that the gradient fill extends like 1 pixel less to the right than the solid color fill. Here's a zoomed in comparison:
![comparison](https://user-images.githubusercontent.com/2974361/231881714-80937e01-dc95-40c4-8140-900c9a87e6ac.png)

I need to look into this more deeply. It could be that it was implemented like this on purpose, so that multiple triangles can be put next to each other seamlessly (each connecting on one edge of the other) for triangle meshes.

**Comment by hageldave** [comment]
Okay I did some more testing. Several things to note:

1. The order of the points (winding clockwise vs counter clockwise) makes a difference in drawing a polyline. So there are no pixel perfect guarantees for polylines in the first place.
```java
int[] xPoints    = { 50, 350, 200};
int[] yPoints    = { 50,  50, 350};
int[] xPointsCC  = {350,  50, 200};
int[] yPointsCC  = { 50,  50, 350 };

Polygon triangle = new Polygon(xPoints, yPoints, 3);
g2d.setColor(Color.WHITE);
g2d.drawPolygon(triangle);

Polygon triangleCC = new Polygon(xPointsCC, yPointsCC, 3);
g2d.setColor(Color.);
g2d.drawPolygon(triangleCC);
```
![winding_difference](https://user-images.githubusercontent.com/2974361/231898115-79f1282d-bb65-46eb-aeb3-bba44244e7fa.png)

2. `BarycentricGradientPaint` currently has a half-pixel shift in coordinates, which is debatable. 
https://github.com/hageldave/JPlotter/blob/878bb5fdca6e9e3c2b13265789e99af2cc3f55b2/jplotter/src/main/java/hageldave/jplotter/util/BarycentricGradientPaint.java#L268-L274

![shift-vs-noshift](https://user-images.githubusercontent.com/2974361/231900505-d4d6278f-a648-4df7-a208-da61b7547850.png)
On the right side is the result without the `+.5f` shift. Left and right edge are consistent with the solid color fill in this case, but the top edge of the gradient fill is now fuzzy.

**Comment by hageldave** [comment]
@hrkalona : all of this is probably not helping with your problem though. Since the regular solid color fill
```java
g2d.setColor(Color.WHITE);
g2d.drawPolygon(triangle);
g2d.setColor(Color.BLUE);
g2d.fillPolygon(triangle);
```
also does not cover the polygon lines perfectly, I'm not so sure if there will be a satisfactory solution for your use case. The problem seems to be rooted in the way polylines are drawn and how line drawing differs from area filling. Maybe there is a workaround for your problem? 
For the `BarycentricGradientPaint` you could shift the `Point2D` coordinates by `+.499f` to get consistent with the solid color fill behavior. You can also try to grow the triangle very slightly for the filling.

**Comment by hrkalona** [comment]
The actual problem appeared when I wanted to use BarycentricGradientPaint on a mesh of triangles.

The original mesh with each triangle rendered with a single color, using graphics2d fill method was working ok. When I tried to use the gradient paint, I was observing lines between the triangles.

 I will post an image in a couple of days, so you can see the actual issue, since I am currently off for Easter vacations.

Thanks for taking the time to look into it!

**Comment by hageldave** [comment]
Exactly.
Also, I will need to do some testing with the mentioned subpixel shift if this will allow seamless filling with polygon.

**Comment by lvcarx** [comment]
Had a brief look at it and it looks like it's better with a shift of 0.001f (no artifacts at the top & same line width on the right/left side).

Smaller values seem to lead to the artifacts at the top again.

![triangle](https://user-images.githubusercontent.com/52721603/232539569-dad27053-5626-4753-b0f2-1a712e0c3b6f.png)

**Comment by hageldave** [comment]
cool, if you could you also try a mesh of triangles and see if there are obvious seams between the triangles that would be great. Until now the code always used fillRect() with a rectangle slightly larger than the triangle. Maybe with the change in subpixel shift, we can also use fillPolygon() and still have seamless connections between adjacent triangles.

**Comment by hrkalona** [comment]
It worked great with fillRect. The meshing is seamless:

![image](https://user-images.githubusercontent.com/1044172/232747575-747e8a97-e449-4654-8c76-334a7b87da32.png)

**Comment by lvcarx** [comment]
With rotation:

![image](https://user-images.githubusercontent.com/52721603/235933253-1496a09d-271c-4a33-8fd7-65b3e6cd59ee.png)

Without rotation:

![image](https://user-images.githubusercontent.com/52721603/235933405-9b5d45b6-ef27-4cf0-b8f4-e461e3db9fbf.png)

**Comment by hageldave** [comment]
Alright, thank you @lvcarx for further looking into this. We see that the polygon clipping is still interfering and results in visible seams between adjacent triangles despite the smaller subpixel shift. This means that the gradient paint is not perfectly compatible with polygon filling in its current state, so it we will continue to use filling with triangle enclosing rectangles.
