### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by gmaczuga** [hageldave/JPlotter#65]
Dear David,

Would it be possible to update dependencies that JPlotter uses lwjgl 3.3.x that seems to run on Mac with M1/M2 ARM cpus?

See: https://github.com/libgdx/libgdx/issues/6084#issuecomment-969253339
And here: https://github.com/LWJGLX/lwjgl3-awt/blob/main/pom.xml (profile lwjgl-natives-macos-aarch64)

Currently on Mac w/ M1 I am using BlankCanvasFallback instead of /*BlankCanvas*/
Hope this update will make things paint faster... much faster.
Thanks!

**Comment by hageldave** [comment]
Hello, thanks for reaching out. 
Unfortunately I cannot test any OS X things since I lack a Mac. Also I have not put any effort into this direction (besides the fallback) since OS X has deprecated OpenGL in 2018. However, it seems to still be supported (?).

So before I try and do anything, I'd like to know if you can run any of the openGL related tests or examples that [lwjgl3-awt](https://github.com/LWJGLX/lwjgl3-awt) provides. Judging from the latest issues on their repository, it may not be working smoothly for OS X.

If this works for you, there is still another problem: The latest release (0.2.0) of lwjgl3-awt has not been deployed to maven central. So it cannot be referenced as a dependency out of the box. So it would need some convincing of the devs to do that, or (not very welcome from my side) a self deployed release of a fork or deployment to a third party maven repository.

**Comment by gmaczuga** [comment]
Hi Dave, let me test on my M1 and I let you know. At the end I can fork all myself :) 
Will keep you updated.

**Comment by gmaczuga** [comment]
True. All ogr.lwjgl.opengl.awt tests fail on M1 Mac.

**Comment by hageldave** [comment]
Sad :/ but you could check if the opengl demos of lwjgl work for you https://github.com/LWJGL/lwjgl3-demos. If they do, it may be possible to support OS X with M1 in lwjgl3-awt. If you have some opengl experience you can try to contribute this functionality.
